version: "3.9"
services:
  filesystem:
    build:
      context: ..
      dockerfile: docker/filesystem.Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
  system:
    build:
      context: ..
      dockerfile: docker/system.Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
  browser:
    build:
      context: ..
      dockerfile: docker/browser.Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
  client:
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    volumes:
      - ..:/app:cached
    ports:
      - "8501:8501"
    command: sleep infinity
